### ISSUE TITLE
Step passes even if upload fails

### ISSUE THREAD

**Issue by ArmyAntSEC** [marcelkalveram/bitrise-step-browserstack-upload#12]
I just had a case where the logs show that the step failed (I cannot see the details, but I assume that some error in the upload caused Browserstack to return some unexpected value). 

I wonder if it would be possible to add validation to the response parsing step and make the step fail if the parsing fails?

I am not very advanced on shell scripts, so I cannot just whip out a PR like that, unfortunately....

![image](https://user-images.githubusercontent.com/55052666/228457086-22d57171-6984-4a3e-8817-b7770736dfd6.png)

**Comment by ArmyAntSEC** [comment]
Closing as there was no reply

**Comment by bukira** [comment]
reopening as I have the same issue and this should be fixed
