### ISSUE TITLE
[Feature Request] Allow custom parameters

### ISSUE THREAD

**Issue by guness** [marcelkalveram/bitrise-step-browserstack-upload#3]
Hello,
Can you please also allow custom parameters like `custom_id` on following request on your next release.

`curl -u "abc:dfg" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@/path/to/app/file/Application-debug.apk" -F 'data={"custom_id": "MyApp"}'`

#4 should fix this.

**Comment by marcelkalveram** [comment]
Feature is available in version 0.1.4.
