### ISSUE TITLE
Space is not allowed in file name

### ISSUE THREAD

**Issue by guness** [marcelkalveram/bitrise-step-browserstack-upload#5]
If file name has space, curl command fails.

**Comment by marcelkalveram** [comment]
@guness Thanks for filing this issue. I'll look into the PR and get back to you

**Comment by marcelkalveram** [comment]
@guness https://github.com/marcelkalveram/bitrise-step-browserstack-upload/pull/4 has been merged and repo been updated to 0.1.4. Thanks for contributing!
