### ISSUE TITLE
Non-relative path?

### ISSUE THREAD

**Issue by alexandrasmith00** [marcelkalveram/bitrise-step-browserstack-upload#6]
When passing the IPA file (I'm using `$BITRISE_IPA_PATH`), it's not referencing properly.  The script looks like `file=@/Users/vagrant/deploy/MyApp.ipa`, but seemingly does not properly find the file.

**Comment by pedrodimoura** [comment]
Same issue here...

**Comment by marcelkalveram** [comment]
@alexandrasmith00 @pedrodimoura thanks for reporting this. Do you mind sharing the part of the log output from Bitrise that's relevant to this issue?
