### ISSUE TITLE
No set environment variable BROWSERSTACK_APP_URL

### ISSUE THREAD

**Issue by FelipeFuenzalidan** [marcelkalveram/bitrise-step-browserstack-upload#7]
Hi guys,
When using the step the BROWSERSTACK_APP_URL environment variable is returning null.
Example:
{"mapped_to":"BROWSERSTACK_APP_URL","value":"null"}
my configuration is:
![image](https://user-images.githubusercontent.com/36612023/91766522-b0b66d00-eba8-11ea-9764-011ec113e449.png)
where $FASTLANE_BUILD_PATH is the path the .apk file.
Log:
![image](https://user-images.githubusercontent.com/36612023/91766670-ef4c2780-eba8-11ea-8397-3869f5ec0bb4.png)

Something that I am doing wrong?

**Comment by rickmanelius** [comment]
I'm having the same issue. I can see the upload occurring similar to the above screenshot, but in a later step when I try to echo out $BROWSERSTACK_APP_URL, it's null. Is it possible that the return value from Browserstack isn't being set?

**Comment by rodolfodotz** [comment]
I'm having the same issue guys. When echo $BROWSERSTACK_APP_URL it's null. Any update?

**Comment by w3ggy** [comment]
~Confirming not working step.~

Now it works when I've added a `customer`field. It is required.

**Comment by marcelkalveram** [comment]
@FelipeFuenzalidan @rickmanelius  @rodolfodotz sorry for not looking into this sooner. Is this still an issue? I haven't been using this step for a while but happy to look into this if it still causes trouble.

**Comment by iAmHarmon** [comment]
@marcelkalveram I'm still experiencing this issue. Going to setup a custom id in the interim.

**Comment by duaatashk** [comment]
@marcelkalveram im facing this issue and a custom ID did not work with me. is there any update about this issue?

**Comment by greenimpala** [comment]
Also seeing this issue but setting a `Custom Id` did work

**Comment by amuthan-sakthivel** [comment]
@greenimpala @marcelkalveram - custom_id field is not working for me. It is not fetching the environment variable and sending it.

Neither the apk gets pushed nor it fetches the correct env variable

![image](https://user-images.githubusercontent.com/98022641/185333187-dcba94d0-d0f2-489b-8897-f9edc41af880.png)

**Comment by greenimpala** [comment]
@amuthan-sakthivel There should be a value for `custom_id` in the CURL form values.
![Screenshot 2022-08-18 at 08 28 01](https://user-images.githubusercontent.com/1367878/185335747-21c7fc60-a1be-47fd-b3d9-15fee1a76e47.png)

**Comment by amuthan-sakthivel** [comment]
@greenimpala - Yes I have mentioned in the workflow. I know it has value

![image](https://user-images.githubusercontent.com/98022641/185336358-f0496a0a-65da-4336-a134-3f59715b9b88.png)

**Comment by greenimpala** [comment]
I just hardcoded a string, it doesn't need to be dynamic It's simply to make this step work

**Comment by amuthan-sakthivel** [comment]
@greenimpala - Yeah got it. In my case I want it to be a variable to define the env of the build so it can be chosen during automation. Anyway thanks for the lead, I will hardcode and check

**Comment by OmerGery** [comment]
https://github.com/marcelkalveram/bitrise-step-browserstack-upload/pull/11 i opened a PR to make this not required

**Comment by dutradotdev** [comment]
+1 facing this issue!!
