### ISSUE TITLE
set -o pipefail is required, without that the step status can be wrong

### ISSUE THREAD

**Issue by jonathan-qa** [marcelkalveram/bitrise-step-browserstack-upload#9]
set -o pipefail is required, without that the step status can be wrong.

I opened a pull request about that with evidences:

**Pull Request** https://github.com/marcelkalveram/bitrise-step-browserstack-upload/pull/8

Please if you need more details talk to me.

Thanks for this step, are helping me a lot.

**Comment by marcelkalveram** [comment]
@jonathan-qa thanks for addressing this. Sorry for the delay. I haven't been paying attention to this repository.
